name: localization_ecommerce
description: An ultra fruit project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_layout_grid: 1.0.3
  flutter_rating_bar: 4.0.0
  go_router: 3.0.3
  shared_preferences: ^2.0.13
  flutter_riverpod: 2.0.0-dev.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add all products images
    - assets/products/
